package View;

import Controller.ComandaController;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author 55319
 */
public class Comanda extends javax.swing.JFrame {

    private final ComandaController controller;


    public Comanda() {
        initComponents();
        controller = new ComandaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCliente1 = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jLabelPedido1 = new javax.swing.JLabel();
        jComboBoxPedido = new javax.swing.JComboBox<>();
        jSpinnerQuantidade = new javax.swing.JSpinner();
        jLabelValor = new javax.swing.JLabel();
        TextValor = new javax.swing.JTextField();
        jLabelPagamento = new javax.swing.JLabel();
        jComboBoxPagamento = new javax.swing.JComboBox<>();
        jLabelData = new javax.swing.JLabel();
        TextData = new javax.swing.JTextField();
        jLabelHora = new javax.swing.JLabel();
        TextHora = new javax.swing.JTextField();
        jLabelObservacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaObservacao = new javax.swing.JTextArea();
        jButtonFinalizar = new javax.swing.JButton();
        jLabelPainel = new javax.swing.JLabel();
        jLabelPapelParede = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCliente1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCliente1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCliente1.setText("Cliente");
        getContentPane().add(jLabelCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 50, -1));

        jComboBoxCliente.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCliente.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxCliente.setToolTipText("");
        jComboBoxCliente.setBorder(null);
        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 410, 40));

        jLabelPedido1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPedido1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPedido1.setText("Pedido");
        getContentPane().add(jLabelPedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 50, -1));

        jComboBoxPedido.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxPedido.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxPedido.setToolTipText("");
        jComboBoxPedido.setBorder(null);
        jComboBoxPedido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPedidoItemStateChanged(evt);
            }
        });
        jComboBoxPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 290, 30));

        jSpinnerQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSpinnerQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, null, 10, 1));
        jSpinnerQuantidade.setBorder(null);
        getContentPane().add(jSpinnerQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 80, 30));

        jLabelValor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Valor");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        TextValor.setBackground(new java.awt.Color(255, 255, 255));
        TextValor.setForeground(new java.awt.Color(0, 0, 0));
        TextValor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        TextValor.setMargin(new java.awt.Insets(2, 10, 2, 10));
        TextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorActionPerformed(evt);
            }
        });
        getContentPane().add(TextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 170, 30));

        jLabelPagamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPagamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPagamento.setText("Forma de Pagamento");
        getContentPane().add(jLabelPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        jComboBoxPagamento.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxPagamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxPagamento.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher forma de pagamento", "Dinheiro", "Pix", "Cartão de Crédito", "Cartão de Débito" }));
        jComboBoxPagamento.setToolTipText("");
        jComboBoxPagamento.setBorder(null);
        jComboBoxPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 200, 30));

        jLabelData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data do Pedido");
        getContentPane().add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        TextData.setBackground(new java.awt.Color(255, 255, 255));
        TextData.setForeground(new java.awt.Color(0, 0, 0));
        TextData.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        TextData.setMargin(new java.awt.Insets(2, 10, 2, 10));
        TextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDataActionPerformed(evt);
            }
        });
        getContentPane().add(TextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 170, 30));

        jLabelHora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("Horário do Pedido");
        getContentPane().add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        TextHora.setBackground(new java.awt.Color(255, 255, 255));
        TextHora.setForeground(new java.awt.Color(0, 0, 0));
        TextHora.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        TextHora.setMargin(new java.awt.Insets(2, 10, 2, 10));
        TextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextHoraActionPerformed(evt);
            }
        });
        getContentPane().add(TextHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 200, 30));

        jLabelObservacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelObservacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservacao.setText("Observação");
        getContentPane().add(jLabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, -1));

        Table.setBackground(new java.awt.Color(204, 204, 204));
        Table.setFont(new java.awt.Font("Segoe UI", 1, 5)); // NOI18N
        Table.setForeground(new java.awt.Color(0, 0, 0));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Pedido", "Quantidade", "Valor", "Forma de Pagamento", "Data", "Hora", "Observação"
            }
        ));
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 280, 470));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 0));

        TextAreaObservacao.setBackground(new java.awt.Color(255, 255, 255));
        TextAreaObservacao.setColumns(20);
        TextAreaObservacao.setForeground(new java.awt.Color(0, 0, 0));
        TextAreaObservacao.setRows(5);
        TextAreaObservacao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 1));
        TextAreaObservacao.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jScrollPane2.setViewportView(TextAreaObservacao);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 410, 60));

        jButtonFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 700, -1, -1));

        jLabelPainel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/painel-login.png"))); // NOI18N
        jLabelPainel.setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().add(jLabelPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 200, 560, 610));

        jLabelPapelParede.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPapelParede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/@hamburgueria.710.png"))); // NOI18N
        getContentPane().add(jLabelPapelParede, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPedidoActionPerformed

    private void TextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorActionPerformed

    private void jComboBoxPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPagamentoActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
       this.controller.agendar();
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jComboBoxPedidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPedidoItemStateChanged
       this.controller.atualizaValor();
    }//GEN-LAST:event_jComboBoxPedidoItemStateChanged

    private void TextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDataActionPerformed

    private void TextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextHoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextArea TextAreaObservacao;
    private javax.swing.JTextField TextData;
    private javax.swing.JTextField TextHora;
    private javax.swing.JTextField TextValor;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxPagamento;
    private javax.swing.JComboBox<String> jComboBoxPedido;
    private javax.swing.JLabel jLabelCliente1;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelPagamento;
    private javax.swing.JLabel jLabelPainel;
    private javax.swing.JLabel jLabelPapelParede;
    private javax.swing.JLabel jLabelPedido1;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerQuantidade;
    // End of variables declaration//GEN-END:variables

 
// GETTER E SETTER
        public JTable getTable() {
        return Table;
    }

    public void setTable(JTable Table) {
        this.Table = Table;
    }

    
    public JComboBox<String> getjComboBoxCliente() {
        return jComboBoxCliente;
    }

    public void setjComboBoxCliente(JComboBox<String> jComboBoxCliente) {
        this.jComboBoxCliente = jComboBoxCliente;
    }

    public JComboBox<String> getjComboBoxPagamento() {
        return jComboBoxPagamento;
    }

    public void setjComboBoxPagamento(JComboBox<String> jComboBoxPagamento) {
        this.jComboBoxPagamento = jComboBoxPagamento;
    }

  
    public JComboBox<String> getjComboBoxPedido() {
        return jComboBoxPedido;
    }

    public void setjComboBoxPedido(JComboBox<String> jComboBoxPedido) {
        this.jComboBoxPedido = jComboBoxPedido;
    }

    public JSpinner getjSpinnerQuantidade() {
        return jSpinnerQuantidade;
    }

    public void setjSpinnerQuantidade(JSpinner jSpinnerQuantidade) {
        this.jSpinnerQuantidade = jSpinnerQuantidade;
    }
    
    public JTextField getTextValor() {
        return TextValor;
    }

    public void setTextValor(JTextField TextValor) {
        this.TextValor = TextValor;
    }

    public JTextArea getTextAreaObservacao() {
        return TextAreaObservacao;
    }

    public void setTextAreaObservacao(JTextArea TextAreaObservacao) {
        this.TextAreaObservacao = TextAreaObservacao;
    }

    public JTextField getTextData() {
        return TextData;
    }

    public void setTextData(JTextField TextData) {
        this.TextData = TextData;
    }

    public JTextField getTextHora() {
        return TextHora;
    }

    public void setTextHora(JTextField TextHora) {
        this.TextHora = TextHora;
    }


    private void iniciar() {
        this.controller.atualizarTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaPedido();
        this.controller.atualizaValor();
    }   
}
